Add REXML development dependency
This fixes test suite errors [[1]] such as:

~~~
... snip ...

  1) Error:
BaseTest#test_to_xml:
LoadError: cannot load such file -- rexml/document

... snip ...
~~~

Other possibility could be to add REXML as a runtime dependency, but that it probably not the right solution, because otherwise the dependency would have to be introduced in ActiveSupport [[2]].

[1]: https://travis-ci.org/github/rails/activeresource/jobs/748631192
[2]: https://github.com/rails/rails/commit/f624ed09abba4a0bae64eb699c9fc2e3f9bdc2dc