Raise errors to suggest completing class configuration
Prior to this commit, the following error is raised when executing
`Base.find`:

```
NoMethodError: undefined method `path' for nil
```

Similarly, `.collection_url` and `.element_url` invocations raise a
similar error:

```
bad argument (expected URI object or URI string)
```

This commit improves the error messages raised when attempting to use an
`ActiveResource::Base` class that hasn't yet been configured with a
`.site` class attribute.

The `Missing site URI` message raised as an `ArgumentError` mirror the
one raised by [ActiveResource::Connection#initialize][].

[ActiveResource::Connection#initialize]: https://github.com/rails/activeresource/blob/v6.2.0/lib/active_resource/connection.rb#L34